### ISSUE TITLE
Unexpected response when using "by_name"

### ISSUE THREAD

**Issue by ehennestad** [apdavison/fairgraph#7]
```
import fairgraph
from fairgraph import KGClient

token = input("Enter token:")
client = KGClient(token)

biologicalSex = fairgraph.openminds.controlledterms.biological_sex.BiologicalSex.by_name("male", client)
print(biologicalSex)
```

Gives the following response (female, not male as expected):

BiologicalSex(name='female', definition='Biological sex that produces egg cells (ova).', description='A female organism typically has the capacity to produce relatively large, usually immobile gametes (reproductive cells), called egg cells (or ova). In the process of fertilization, an egg cell (ovum) fuses with a smaller, usually mobile male gametes, called sperm cells (or spermatozoa).', interlex_identifier=IRI(http://uri.interlex.org/base/ilx_0104150), preferred_ontology_identifier=IRI(http://purl.obolibrary.org/obo/PATO_0000383), space=controlled, id=https://kg.ebrains.eu/api/instances/7606df11-c8d9-4ca4-98e3-8167ce6f432b)

**Comment by apdavison** [comment]
see https://github.com/HumanBrainProject/fairgraph/issues/64
